import type { Metadata, Viewport } from "next";
import { Noto_Sans } from "next/font/google";

import "./globals.css";
import "react-modern-drawer/dist/index.css";
import { Providers } from "@/provider";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Choose the required font weights
  variable: "--font-noto", // Optional: Define a CSS variable
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: "#626F47",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
